### DISCUSSION TITLE
Web app (or website) where users can run these rules online on files

### DISCUSSION THREAD

**Discussion by gaurav-nelson** [redhat-documentation/vale-at-red-hat#34] [Ideas]
I want to present my idea to the hive mind, and I want to know if this is worth spending time on. 

Current implementation involves installing Vale and then adding rules and configuration in one's repository to test and see the result. However, I want to create a 🌐 web app that allows users to test the rules and see the output for a file without any configuration. 

I might already have a proof-of-concept for the curious. 😉 

EDIT: 
And we can rope in #29  So maybe we can have a web app running our rules and spaCy and users can lint their files online similar to https://hemingwayapp.com/ (too ambitious, I know) and we can use the same web service to host the spaCy endpoint for grammar-based rules.

**Comment by aireilly** [comment]
Looks very cool, and a nice way to get people linting without fuss.

**Reply by rolfedh** [reply]
+10

**Reply by briandooley** [reply]
Liking this a lot. +10

**Comment by themr0c** [comment]
You can use Eclipse Che hosted by Red Hat. See: https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/.

Add the Vale extension to your devfile:

```
  - type: chePlugin
    reference: https://che-plugin-registry-main.surge.sh/v3/plugins/errata-ai/vale-server/latest/meta.yaml
    alias: vale-vscode
    preferences:
      vale.core.useCLI: true
```

Example devfile using vale: https://github.com/eclipse/che-docs/blob/master/devfile.yaml
