### ISSUE TITLE
Create a Vale rule that highlights custom CR names and suggests an example name

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#825]
Sometimes CR names include customer sensitive information. For example:

```yaml
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: "customer-senstive-name"
  namespace: openshift-sriov-network-operator
```

Write a vale rule that highlights any CR name field that does not match the following best practice naming (pseudo code): 

`example-$(to_kebab_case(value_of(kind_field))`

https://vale.sh/docs/topics/actions/
